controller_manager:
  ros__parameters:

    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    right_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


right_hand_controller:
  ros__parameters:

    joints:
      - right_thumb_actuator_joint
      - right_index_actuator_joint
      - right_middle_actuator_joint
      - right_ring_actuator_joint
      - right_little_actuator_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity